<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="rParcial.aspx.cs" Inherits="Parcial1_UI.Registros.rParcial" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Contenido" runat="server">
    <div class="panel panel-primary">
        <div class="panel-body">
             <div class="form-horizontal col-md-12" role="form">
                 <div class="form-group row">
                 <label for="Id" class="col-sm-1 col-form-label">ID</label>
                  <div class="col-xs-1 col-md-1">
                  <asp:TextBox runat="server" type="number" CssClass="form-control input-sm" ID="IDTextBox"></asp:TextBox>
                   <asp:RequiredFieldValidator ID="RFVID" runat="server" MaxLength="100" ControlToValidate="IDTextBox" ErrorMessage="Obligatorio" ForeColor="Black" Display="Dynamic" SetFocusOnError="True"></asp:RequiredFieldValidator>
                  </div>
                  <div class="col-xs-1">
                  <asp:Button Text="Buscar" class="btn btn-dark btn-sm" CausesValidation="false" style="color:#fff" runat="server" ID="BuscarButton" OnClick="BuscarButton_Click" />
                  </div>
                     <label for="Fecha" class="col-sm-1 col-form-label">Fecha</label>
                     <div class="col-md-3">
                         <asp:TextBox runat="server" type="date" CssClass="form-control" ID="FechaTextBox"></asp:TextBox>
                         <asp:RequiredFieldValidator ID="RFVFecha" runat="server" MaxLength="100" ControlToValidate="FechaTextBox" ErrorMessage="Obligatorio" ForeColor="Black" Display="Dynamic" SetFocusOnError="True"></asp:RequiredFieldValidator>
                     </div>
                 </div>
                 <div class="form-group row">
                 <label for="Estudiante" class="col-sm-1 col-form-label">Estudiante</label>
                     <div class="col-md-5">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="EstudianteTextBox"></asp:TextBox>
                         <asp:RequiredFieldValidator ID="RFVEstudiante" runat="server" MaxLength="100" ControlToValidate="EstudianteTextBox" ErrorMessage="Obligatorio" ForeColor="Black" Display="Dynamic" SetFocusOnError="True"></asp:RequiredFieldValidator>
                     </div>
                 </div>
                 <div class="form-group row">
                 <label for="Categoria" class="col-sm-1 col-form-label">Categoria</label>
                      <div class="col-md-2">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="CategoriaTextBox"></asp:TextBox>
                     </div>
                     <label for="Valor" class="col-sm-1 col-form-label">Valor</label>
                      <div class="col-md-2">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="ValorTextBox"></asp:TextBox>
                     </div>
                    <label for="Logrado" class="col-sm-1 col-form-label">Logrado</label>
                      <div class="col-md-2">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="LogradoTextBox"></asp:TextBox>
                     </div>
                     <div class="col-md-1">
                         <asp:Button class="btn btn-outline-success btn-md" CausesValidation="false" runat="server" ID="AgregarGrid" Text="Agregar" OnClick="AgregarGrid_Click"/>
                     </div>
                 </div>

                 <asp:GridView ID="Grid" runat="server" DataKeyNames="EvaluacionDetalleId" CssClass="table-responsive-lg align-items-center" AutoGenerateDeleteButton="True" OnRowDeleting="Grid_RowDeleting" AutoGenerateColumns="false">
                     <Columns>
                        <asp:BoundField DataField="Categoria" HeaderText="Categoria" /><asp:BoundField />
                         <asp:BoundField DataField="Valor" HeaderText="Valor" /><asp:BoundField />
                         <asp:BoundField DataField="Logrado" HeaderText="Logrado" /><asp:BoundField />
                         <asp:BoundField DataField="Perdido" HeaderText="Perdido" /><asp:BoundField />
                     </Columns>
                 </asp:GridView>

 <br />
                 <div class="form-group row">
                 <label for="Total" class="col-sm-1 col-form-label">Total</label>
                     <div class="col-md-2">
                         <asp:TextBox runat="server" CssClass="form-control input-sm" ID="TotalTextBox" ReadOnly="true"></asp:TextBox>
                     </div>
                 </div>
             </div>
            <asp:Label Text="" runat="server" CssClass="col-form-label-lg" ID="Mensaje"></asp:Label>
        </div>
        <div class="panel-footer">
            <div class="text-center">
                <div class="form-group" style="display: inline-block">

                  <asp:Button Text="Nuevo" class="btn btn-warning btn-sm" CausesValidation="false" style="color:#fff" runat="server" ID="NuevoButton" OnClick="NuevoButton_Click"  />
                  <asp:Button Text="Guardar" class="btn btn-success btn-sm" runat="server" ID="GuardarButton" OnClick="GuardarButton_Click"/>
                  <asp:Button Text="Eliminar" class="btn btn-danger btn-sm" CausesValidation="false" runat="server" ID="EliminarButton" OnClick="EliminarButton_Click" />

                </div>
            </div>
       </div>
    </div>
</asp:Content>
